# Lightweight docker-compose which only has the datastores, so you can still develop rails locally

# To use, run docker-compose up -d
version: '3.4'

services:

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
