# Docker Compose for a development version of Pushmi-Pullyu
# with the full HydraNorth
version: '3'


services:
  hydranorth:
    image: "ualibraries/hydra_north:deb"
    env_file:
      - .env-hydranorth
    volumes: 
      # di_docker_hydranorth expects codebase in `app` within the container
      - ${LOCAL_SRC_PATH:-../../HydraNorth}:/app

  swift: 
    image: "ualibraries/swift_dev"

  pushmi-pullyu:
    # assumes GitHup repo clone & run `docker-compose up` from repo root
    # `..` context changes to `docker` dir, change to root of repo
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile.pushmi_pullyu.development
    volumes: 
      - ..:/app/pushmi-pullyu
    depends_on:
      - swift
