# Docker Compose for a development version of Pushmi-Pullyu
# 
version: '3'

services:
  hydranorth:
    image: "ualibraries/hydra_north:deb"
    env_file:
      - .env-hydranorth
    volumes: 
      # di_docker_hydranorth expects codebase in `app` within the container
      - ${LOCAL_SRC_PATH:-../../HydraNorth}:/app
    ports:
      - "3000:3000"
      - "8983:8983"

  swift: 
    image: "ualibraries/swift_dev"

  pushmi-pullyu:
    # assumes GitHup repo clone & run `docker-compose up` from repo root
    # `..` context changes to `docker` dir, change to root of repo
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile.pushmi_pullyu.development
    env_file:
      - .env-pushmi_pullyu
    volumes: 
      - ..:/app
    depends_on:
      - swift
    stdin_open: true # help debug: keep STDIN open even if not attached
    tty: true # help debug: Allocate a pseudo-TTY

